1 # without loops we need to write each task for each packag
---
- name: to install the packages
  hosts: all
  become: true
  tasks: 
  - name: install git
    apt:
      name: git
      state: present
  - name: install tree
    apt:
      name: tree
      state: present
  - name: Install unzip
    apt:
      name: unzip
      state: present


2 # with loops
---
- name: to install packages
  hosts: all
  become: true
  tasks: 
  - name: Install multiple packages
    apt:
      name: "{{item}}"
      state: present
    with_items:
    - git
    - unzip
    - tree


3 #  install packages using a list
---
- name: 
  hosts: all
  become: true
  tasks: 
  - name: Install multiple packages
    apt:
      name: ['git', 'unzip', 'tree', 'wget']
      state: present



4  # Create users using loop
---
- name: creating users 
  hosts: all
  become: true
  tasks:
  - name: Create users
    user:
      name: "{{item}}"
      create_home: yes
    with_items:
    - chandu
    - hari


5 # creating users one with homedir and other  without homedir

---
- name: creating users 
  hosts: all
  become: true
  tasks: 
  - name: create users
    user: 
      name: "{{item.name}}"
      create_home: "{{item.create_home}}"
    with_items:
    - {'name': 'chandu', 'create_home': 'yes'}
    - {'name': 'hari', 'create_home': 'no'}




---
- name: 
  hosts: all
  become: true
  tasks:
  - name: create users
    user:
      name: {{items}}
      create_home: yes 
    with_items:
    - chandu
    - shiva


