# create a varaible file
# vi variable.yaml
courseName: Devops
Batch: 21

# create a playbook.yaml

# vi installhttpd.yaml
---
- hosts: all
  become: true
  vars_files:
  - variable.yaml
  tasks:
  - name: Install Apache httpd
    yum:
      name: httpd
      state: present
  - name: Copy the html file 
    template:  # previously copy
      src: index.html
      dest: /var/www/html/index.html
    notify: 
    - Restart the service 
  handlers:
  - name: Restart the service 
    service: 
      name: httpd
      enabled: true
      state: restarted


# if we can pass the variables in the Runtime the run time variables comes in to the presidence 
# and we can pass the runtime variables in 2 ways 


# ansible-playbook  -i inv_file  installhttpd.yaml --extra-vars courseName=Docker 
# ansible-playbook -i inv_file installhttpd.yaml  -e batchNumber=100

pass the varaible files dynamically

# vi dev_vars.yaml
courseName: GCP
batchNumber: 21

# vi prod_vars.yaml
courseName: Azure
batchNumber: 24

vi playbook.yaml

---
- name: to install httpd
  hosts: all
  become: true
  vars_files:
  - "{{env}}_vars.yaml"
  tasks:
  - name: Install  httpd
    yum:
      name: httpd
      state: present
  - name: Copy the html file 
    template:  # previously copy
      src: index.html
      dest: /var/www/html/index.html
    notify: 
    - Restart the service 
  handlers:
  - name: Restart the service 
    service: 
      name: httpd
      enabled: true
      state: restarted

# ansible-playbook -i inv_file playbook.yaml  -e env=prod
# ansible-playbook -i inv_file playbook.yaml --extra-vars env=dev